ci: ios e2e

diff --git a/.github/workflows/merge-request.yml b/.github/workflows/merge-request.yml
--- a/.github/workflows/merge-request.yml
+++ b/.github/workflows/merge-request.yml
@@ -56,6 +56,9 @@ jobs:
       pull-requests: write
       deployments: write
       issues: write
+    outputs:
+      deployment_url: ${{ steps.deploy-web.outputs.deployment_url }}
+      update_url: ${{ steps.extract-preview-url.outputs.update_url }}
     steps:
       - name: Check for EXPO_TOKEN
         run: |
@@ -84,10 +87,21 @@ jobs:
         run: yarn install
 
       - name: Create preview
+        id: create-preview
         uses: expo/expo-github-action/preview@v8
         with:
           command: eas update --channel development --auto
           working-directory: packages/app
+
+      - name: Extract Preview URL
+        run: |
+          update_url=$(jq -r '.updateUrl // empty' <<< "${{ steps.create-preview.outputs.result }}")
+          if [ -z "$update_url" ]; then
+            echo "Failed to retrieve update URL."
+            exit 1
+          fi
+          echo "update_url=$update_url" >> $GITHUB_OUTPUT
+        id: extract-preview-url
 
       - name: Build web app
         working-directory: packages/app
@@ -222,6 +236,10 @@ jobs:
       - name: Install App on Simulator
         run: |
           xcrun simctl install booted "${{ steps.download-build.outputs.app_path }}"
+
+      - name: Open Preview URL
+        run: |
+          xcrun simctl openurl booted "${{ needs.eas-deploy.outputs.update_url }}"
 
       - name: Run Maestro UI tests
         run: |
